/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.guy_sw.versioning.client;

public class Main {

    public static void main(String[] args) {
        System.out.println("Welcome To Versioning Project Client!");
    }
}
